/* eslint-disable react-refresh/only-export-components */
import {
  Home,
  Car,
  Fuel,
  ShoppingCart,
  ShoppingBag,
  Utensils,
  Coffee,
  Pizza,
  Heart,
  HeartPulse,
  Stethoscope,
  Pill,
  GraduationCap,
  BookOpen,
  Plane,
  Bus,
  Bike,
  Wallet,
  Landmark,
  PiggyBank,
  TrendingUp,
  CreditCard,
  Receipt,
  Banknote,
  DollarSign,
  Gift,
  Gamepad2,
  Music,
  Film,
  Dumbbell,
  Shirt,
  Baby,
  Dog,
  Wrench,
  Zap,
  Droplet,
  Flame,
  Wifi,
  Smartphone,
  Building2,
  Briefcase,
  Church,
  Scissors,
  Tag,
  CircleDollarSign,
  ArrowLeftRight,
  CircleEllipsis,
  type LucideIcon,
} from 'lucide-react';

/** Ícones disponíveis para categorias (nome em kebab-case → componente). */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  home: Home,
  car: Car,
  fuel: Fuel,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  heart: Heart,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  plane: Plane,
  bus: Bus,
  bike: Bike,
  wallet: Wallet,
  landmark: Landmark,
  'piggy-bank': PiggyBank,
  'trending-up': TrendingUp,
  'credit-card': CreditCard,
  receipt: Receipt,
  banknote: Banknote,
  'dollar-sign': DollarSign,
  gift: Gift,
  'gamepad-2': Gamepad2,
  music: Music,
  film: Film,
  dumbbell: Dumbbell,
  shirt: Shirt,
  baby: Baby,
  dog: Dog,
  wrench: Wrench,
  zap: Zap,
  droplet: Droplet,
  flame: Flame,
  wifi: Wifi,
  smartphone: Smartphone,
  building: Building2,
  briefcase: Briefcase,
  church: Church,
  scissors: Scissors,
  tag: Tag,
  'circle-dollar-sign': CircleDollarSign,
  'arrow-left-right': ArrowLeftRight,
  'circle-ellipsis': CircleEllipsis,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

/** Renderiza o ícone de uma categoria pelo nome, com fallback em "tag". */
export function CategoryIcon({
  name,
  className = 'h-4 w-4',
}: {
  name?: string | null;
  className?: string;
}) {
  const Icon = (name && CATEGORY_ICONS[name]) || Tag;
  return <Icon className={className} strokeWidth={1.8} />;
}
